[package]
name = "rp2350_arm_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mg = { path = "../../fwk", features = ["smp"] }

