[package]
name = "stm32f030_demo_board"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mg = { path = "../../fwk" }

